xhost +SI:localuser:$USER

export _JAVA_AWT_WM_NONREPARENTING=1
xsetroot -cursor_name left_ptr
xset r rate 200 60

# run compositor to avoid tearing
picom --xrender-sync-fence -b

# eyecare
redshift -P -O 4500

# turn off touchpad
/usr/local/bin/touchpad-off

# emacs
emacs.font: DejaVu Sans Mono-12
emacs --daemon
exec emacsclient -c
