abbr g 'git'
abbr ga 'git add'
abbr gs 'git status'
abbr gb 'git branch'
abbr gco 'git checkout'
abbr gc 'git commit -v'
abbr gc! 'git commit --ammend'
abbr grbi 'git commit rebase -i'
abbr gclean 'git clean -fd'
abbr gd 'git diff'
abbr gk 'gitk'
abbr gg 'git grep --break --heading -n'
abbr gp 'git push'
